### ISSUE TITLE
GSD

### ISSUE THREAD

**Issue by swedenbas** [scarnecchia/GSD_calc#3]
Is the GSD calculator correct? The final result of a calculation I made should be 1 cm, but in your calculator, it becomes 0.1 cm. I might be wrong, but if I´m not I thought it would be good for you to knew :-)

**Comment by scarnecchia** [comment]
I'll take a look, it's entirely possible I introduced an error at some point. Could you give me the sensor size and altitude you were calculating for?

**Comment by swedenbas** [comment]
Hello,
Pixel pitch 17 microns, altitude 1000 meter and focal length 26 mm, I think  GSD should be 65.4 cm, but when I'm trying your calculator, i get 6.54 cm. Otherwise, I think it's a very good calculator.
Date: Fri, 13 May 2016 12:36:41 -0700

**Comment by scarnecchia** [comment]
@swedenbas So I think I've discovered the issue. You're likely not using pixel pitch (that is, the distance between the center of two pixels) but pixel size, which is the area covered by a pixel. On my end, I erroneously labeled the unit as mm^2 when indeed it should have been mm. That issue should be fixed now! Cheers!
